In [62]:
import numpy as np

## 1. Creating Arrays of diff dimensions


In [63]:
arr1d= np.array([1,2,3,4,5,6])
print("1D array :")
print(arr1d)

1D array :
[1 2 3 4 5 6]


In [64]:
arr2d = np.array([[1,2,3,],
                 [4,5,6],
                 [7,8,9]])
print("2D array:")
print(arr2d)

2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [65]:
arr3d = np.array([[[1, 2], [3, 4]],
                    [[5, 6], [7, 8]],
                    [[9, 10], [11, 12]]])
print("3D array:")
print(arr3d)

3D array:
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


## 2.Array Dimensions and Data Types


In [66]:
for name, a in [("1d arr", arr1d), ("2d arr", arr2d), ("3d arr", arr3d)]:
    print(f"{name}: ndim={a.ndim}, shape={a.shape}, size={a.size}, dtype={a.dtype}")

1d arr: ndim=1, shape=(6,), size=6, dtype=int64
2d arr: ndim=2, shape=(3, 3), size=9, dtype=int64
3d arr: ndim=3, shape=(3, 2, 2), size=12, dtype=int64


In [67]:
int_arr = np.array([1.9, 2.5, 3.1], dtype=np.int32)
float_arr = np.array([1, 2, 3], dtype=np.float64)
print("int_arr:", int_arr, int_arr.dtype)
print("float_arr:", float_arr, float_arr.dtype)


int_arr: [1 2 3] int32
float_arr: [1. 2. 3.] float64


## 3. Indexing and Slicing

In [68]:
print("arr_1d:", arr1d)
print("first element:", arr1d[0])
print("last element:", arr1d[-1])
print("slice [1:4]:", arr1d[1:4])
print("alternate element:", arr1d[::2])

arr_1d: [1 2 3 4 5 6]
first element: 1
last element: 6
slice [1:4]: [2 3 4]
alternate element: [1 3 5]


In [69]:
print("2d arr :")
print(arr2d)
print("\nElement at row 1, col 2:", arr2d[1, 2])
print("\nFirst row:", arr2d[0])
print("First column:", arr2d[:, 0])
print("\nSub-matrix (rows 0-1, cols 1-2):")
print(arr2d[0:2, 1:3])

2d arr :
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Element at row 1, col 2: 6

First row: [1 2 3]
First column: [1 4 7]

Sub-matrix (rows 0-1, cols 1-2):
[[2 3]
 [5 6]]


In [70]:
print("3d arr shape:", arr3d.shape)
print("First block:")
print(arr3d[0])
print("\nElement at [1, 0, 1]:", arr3d[1, 0, 1])

3d arr shape: (3, 2, 2)
First block:
[[1 2]
 [3 4]]

Element at [1, 0, 1]: 6


## 4. Reshaping Arrays


In [71]:
original = np.arange(12)
print("Original:", original, "shape:", original.shape)

reshaped_2d = original.reshape(3, 4)
print("\nReshaped to (3, 4):")
print(reshaped_2d)

reshaped_3d = original.reshape(2, 3, 2)
print("\nReshaped to (2, 3, 2):")
print(reshaped_3d)

Original: [ 0  1  2  3  4  5  6  7  8  9 10 11] shape: (12,)

Reshaped to (3, 4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Reshaped to (2, 3, 2):
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [72]:
auto_reshape = original.reshape(4, -1)
print("Reshaped to (4, -1):")
print(auto_reshape)

flat = reshaped_2d.flatten()
print("\nFlattened:", flat)

Reshaped to (4, -1):
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

Flattened: [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [73]:
print("Original 2D:")
print(arr2d)
print("\nTransposed:")
print(arr2d.T)

Original 2D:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Transposed:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


## 5.Arrays with Built-in Functions


In [74]:
zeros_arr = np.zeros((2, 3))
ones_arr = np.ones((3, 3))
full_arr = np.full((2, 2), 3)
identity_arr = np.eye(4)

print("zeros((2,3)):")
print(zeros_arr)
print("\nones((3,3)):")
print(ones_arr)
print("\nfull((2,2), 7):")
print(full_arr)
print("\nidentity matrix eye(4):")
print(identity_arr)

zeros((2,3)):
[[0. 0. 0.]
 [0. 0. 0.]]

ones((3,3)):
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

full((2,2), 7):
[[3 3]
 [3 3]]

identity matrix eye(4):
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [75]:
range_arr = np.arange(0, 20, 2)
print("arange(0, 20, 2):", range_arr)

lin_arr = np.linspace(0, 1, 5)
print("linspace(0, 1, 5):", lin_arr)

arange(0, 20, 2): [ 0  2  4  6  8 10 12 14 16 18]
linspace(0, 1, 5): [0.   0.25 0.5  0.75 1.  ]


## 6. Mathematical and Vectorized Operations


In [76]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print("a + b =", a + b)
print("a - b =", a - b)
print("a * b =", a * b)
print("b / a =", b / a)
print("a ** 2 =", a ** 2)
print("sqrt(b) =", np.sqrt(b))

a + b = [11 22 33 44]
a - b = [ -9 -18 -27 -36]
a * b = [ 10  40  90 160]
b / a = [10. 10. 10. 10.]
a ** 2 = [ 1  4  9 16]
sqrt(b) = [3.16227766 4.47213595 5.47722558 6.32455532]


In [77]:
angles = np.array([0, np.pi/2, np.pi])
print("sin(angles):", np.sin(angles))
print("exp([1,2,3]):", np.exp(np.array([1, 2, 3])))
print("log([1, np.e, np.e**2]):", np.log(np.array([1, np.e, np.e**2])))

sin(angles): [0.0000000e+00 1.0000000e+00 1.2246468e-16]
exp([1,2,3]): [ 2.71828183  7.3890561  20.08553692]
log([1, np.e, np.e**2]): [0. 1. 2.]


In [78]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])

print("Element-wise multiply:")
print(m1 * m2)
print("\nMatrix multiplication (dot product):")
print(m1 @ m2)

Element-wise multiply:
[[ 5 12]
 [21 32]]

Matrix multiplication (dot product):
[[19 22]
 [43 50]]


## 7. Broadcasting


In [79]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("matrix + 10:")
print(matrix + 10)

matrix + 10:
[[11 12 13]
 [14 15 16]]


In [80]:
row_vector = np.array([100, 200, 300])
print("matrix shape:", matrix.shape, "| row_vector shape:", row_vector.shape)
print("\nmatrix + row_vector (broadcast across rows):")
print(matrix + row_vector)

matrix shape: (2, 3) | row_vector shape: (3,)

matrix + row_vector (broadcast across rows):
[[101 202 303]
 [104 205 306]]


In [81]:
col_vector = np.array([[1], [2]])
print("matrix shape:", matrix.shape, "| col_vector shape:", col_vector.shape)
print("\nmatrix + col_vector (broadcast across columns):")
print(matrix + col_vector)

matrix shape: (2, 3) | col_vector shape: (2, 1)

matrix + col_vector (broadcast across columns):
[[2 3 4]
 [6 7 8]]


## 8. Boolean Masking


In [82]:
data = np.array([15, 3, 42, 8, 91, 27, 6, 55])
print("data:", data)

mask = data > 20
print("\nBoolean mask (data > 20):", mask)
print("Filtered values (data > 20):", data[mask])

data: [15  3 42  8 91 27  6 55]

Boolean mask (data > 20): [False False  True False  True  True False  True]
Filtered values (data > 20): [42 91 27 55]


In [83]:
combo_mask = (data > 10) & (data < 50)
print("Values between 10 and 50:", data[combo_mask])


data_copy = data.copy()
data_copy[data_copy < 10] = 0
print("\nAfter zeroing values < 10:", data_copy)

Values between 10 and 50: [15 42 27]

After zeroing values < 10: [15  0 42  0 91 27  0 55]


## 9. Common Aggregate Functions


In [84]:
scores = np.array([[85, 90, 78],
                    [92, 88, 95],
                    [70, 65, 80],
                    [88, 91, 84]])
print("scores (rows = player, cols = runs):")
print(scores)

scores (rows = player, cols = runs):
[[85 90 78]
 [92 88 95]
 [70 65 80]
 [88 91 84]]


In [85]:
print("Sum of all scores:", scores.sum())
print("Mean of all scores:", scores.mean())
print("Min runs:", scores.min())
print("Max runs:", scores.max())
print("Median of all runs:", np.median(scores))
print("Standard deviation:", round(scores.std(), 2))

Sum of all scores: 1006
Mean of all scores: 83.83333333333333
Min runs: 65
Max runs: 95
Median of all runs: 86.5
Standard deviation: 8.72


In [86]:
print("Average per player (axis=1, across runs):", scores.mean(axis=1))
print("Average runs (axis=0, across players):", scores.mean(axis=0))
print("\nHighest run by player:", scores.max(axis=0))
print("Lowest run per player:", scores.min(axis=1))

Average per player (axis=1, across runs): [84.33333333 91.66666667 71.66666667 87.66666667]
Average runs (axis=0, across players): [83.75 83.5  84.25]

Highest run by player: [92 91 95]
Lowest run per player: [78 88 65 84]
